import Typography from "@mui/material/Typography";

export default function Home() {
  return (
    <div>
      <head>
        <title>Thai Crossword</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <body>
        <Typography variant="h1" component="h1">
          Welcome to Thai Crossword!
        </Typography>
  
      </body>
    </div>
  );
}